### ISSUE TITLE
How to choose time for spending mails?

### ISSUE THREAD

**Issue by anzolo** [Hopebaytech/redmine_mail_reminder#39] opened 2015-06-18 06:30 UTC
I want to get mails on 9 a.m. everyday. How i can configure this?

**Comment by Androc** [comment] 2015-06-18 06:33
Configure your reminder to be daily/everyday and set up your cron to be launched at 9am :
```
0 9 * * * cd redmine/ && rake reminder:exec RAILS_ENV="production"
```

The problem is, if you want to send mails at 9am and other reminders at 10am, it is not possible at the moment.

**Comment by jcppkkk** [comment] 2015-06-18 06:40
Maybe we can use https://github.com/javan/whenever to improve this part

**Comment by Androc** [comment] 2015-06-18 06:46
Would it solve the problem of sending different reminders at different times of the day ?

**Comment by jcppkkk** [comment] 2015-06-18 07:20
@Androc yes, i want to replace cronjob wih ruby implementation. So user user can setup different  schedules. After a little more survey i think [clockwork](https://github.com/tomykaira/clockwork) can fit the requirement.

- It has an ability to load scheduled tasks from database (through ActiveRecord or any arbitrary source).
- Also it can dynamically update scheduled tasks by polling data updates from the DB.

**Comment by Androc** [comment] 2015-06-18 07:32
@jcppkkk it seems great. Adding this ability to your plugin will ease its installation and its usability and making it more flexible.

**Comment by anzolo** [comment] 2015-06-18 07:47
I use bitnami redmine stack on windows server. in that case, i must use win sheduler for solve my task?

**Comment by Androc** [comment] 2015-06-18 07:48
Yes, follow this : https://github.com/Hopebaytech/redmine_mail_reminder#installation---windows

**Comment by anzolo** [comment] 2015-06-18 07:50
ok, thanx!

**Comment by Androc** [comment] 2015-06-18 07:53
My pleasure :)
Don't forget to close the issue when you really solved your problem.

**Comment by anzolo** [comment] 2015-06-22 06:23
Thanx, problem is fixed!

**Closed** 2015-06-22 06:24 UTC

**Comment by Androc** [comment] 2015-06-22 07:16
Good news :)
